{
  den,
  ...
}:
{
  den.aspects.yggdrasil.nixos = { config, lib, ... }:
  let
    toIpv6Address = prefix64: seed: lib.pipe seed [
      (builtins.hashString "sha256")
      (x: map (i: builtins.substring (4 * i) 4 x) [ 0 1 2 3 ])
      (x: builtins.concatStringsSep ":" ([ prefix64 ] ++ x))
    ];
    toIpv6Address' = toIpv6Address config.ygg.prefix;
    vhost = { name, ... }: {
      options = {
        ygg = lib.mkOption {
          description = "autogenerated yggdrasil address or manually set one";
          type = lib.types.str;
          default = toIpv6Address' name;
        };
        localAddr = lib.mkOption {
          description = "local address to forward ygg trafic";
          type = lib.types.str;
          default = "localhost";
        };
        localPort = lib.mkOption {
          description = "port to forward ygg trafic";
          type = lib.types.port;
        };
        domain = lib.mkOption {
          description = "domain to be used by a local dns host";
          type = lib.types.str;
          default = "${name}.ygg";
        };
      };
    };

    vhost' = lib.types.submodule vhost;
  in
  {
    options = {
      vhosts = lib.mkOption {
        description = "Attrset of HTTP virtual-hosts to create Yggdrasil addresses for.";
        type = lib.types.attrsOf vhost';
      };
      ygg = lib.mkOption {
        description = "custom yggdrasil options";
        type = lib.types.submodule ({
          options = {
            prefix = lib.mkOption {
              description = "yggdrasil prefix";
              type = lib.types.str;
            };
            address = lib.mkOption {
              description = "yggdrasil address";
              type = lib.types.str;
            };
          };
        });
      };
    };
    config = let
      yggIfName = config.services.yggdrasil.settings.IfName;
    in {
      boot.kernel.sysctl."net.ipv6.conf.all.forwarding" = 1;

      networking = {
        firewall = {
          allowedTCPPorts = [ 80 443 22 ];
          allowedUDPPorts = [ 80 443 22 ];
        };

        interfaces.${yggIfName}.ipv6.addresses =
          (lib.mapAttrsToList (_: { ygg, ... }:
            { address = ygg; prefixLength = 64; }
          ) config.vhosts);
      };
      
      services = {
        yggdrasil = {
          enable = true;
          group = "wheel";
          openMulticastPort = lib.mkDefault true;
          settings = {
            IfName = lib.mkDefault "ygg0";
            Peers = [
              "tls://satori.nadeko.net:44442"
              "tcp://ygg.nadeko.net:44441"
              "tcp://ygg-1.okade.pro:20000"
            ];
            NodeInfo = {
              name = config.networking.hostName;
              location = "Wherever Fuyuka's T14 gen 4 goes";
            };
          };
        };

        radvd = {
          enable = true;
          config = ''
            interface ${config.services.yggdrasil.settings.IfName}
            {
              AdvSendAdvert on;
              prefix ${config.ygg.prefix}::/64 {
                AdvOnLink on;
                AdvAutonomous on;
              };
              route 200::/8 {};
            };
          '';
        };
      };

      environment.etc."ygg-addresses".text = builtins.concatStringsSep "\n"
        (lib.mapAttrsToList (n: v: "<${n}> [${v.ygg}] -> ${v.localAddr}:${lib.toString v.localPort}") config.vhosts);
    };
  };
}
